### ISSUE TITLE
Outdated links leads to broken pages

### ISSUE THREAD

**Issue by joshxfi** [gdgoc-usls/landing#20]
![image](https://github.com/user-attachments/assets/e3d67cab-4f60-48a3-8466-a40a9c12ee0b)

Resolve the broken links with the following urls:
- Google Awards: https://gdsc-awards.omsimos.com/
- Solcha 2023: https://gdsc.omsimos.com/solcha-info

**Comment by seolyam** [comment]
> ![image](https://private-user-images.githubusercontent.com/69457996/398080774-e3d67cab-4f60-48a3-8466-a40a9c12ee0b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5NjcwNjcsIm5iZiI6MTczNDk2Njc2NywicGF0aCI6Ii82OTQ1Nzk5Ni8zOTgwODA3NzQtZTNkNjdjYWItNGY2MC00OGEzLTg0NjYtYTQwYTljMTJlZTBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIzVDE1MTI0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3MTUwMmM1NjMzNThiYzE3NzdjMzZlNjRiNTcwMDdhZDU0MGI0NzkwZGQyZjk2OTFiMjBhYzgzYWIzNjdmOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CrQZ5KjOfQcGcbAymGqOCZUJXey5ZpiW8abxkDIWpz4)
> 
> Resolve the broken links with the following urls:
> 
>     * Google Awards: https://gdsc-awards.omsimos.com/
> 
>     * Solcha 2023: https://gdsc.omsimos.com/solcha-info

Done, already pushed to dev branch as you have permitted
