### ISSUE TITLE
Replace events from '22 to '24

### ISSUE THREAD

**Issue by joshxfi** [gdgoc-usls/landing#21]
Seems like events from '22 have been all deleted which leads to all the pages to 404. Let's replace the old events with the ones from '24.

![image](https://github.com/user-attachments/assets/7df0e27a-07b0-4dfb-b09a-309ba011ef22)

**Comment by seolyam** [comment]
done!

**Comment by seolyam** [comment]
> Seems like events from '22 have been all deleted which leads to all the pages to 404. Let's replace the old events with the ones from '24.
> 
> ![image](https://private-user-images.githubusercontent.com/69457996/398197680-7df0e27a-07b0-4dfb-b09a-309ba011ef22.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwNDA4MDQsIm5iZiI6MTczNTA0MDUwNCwicGF0aCI6Ii82OTQ1Nzk5Ni8zOTgxOTc2ODAtN2RmMGUyN2EtMDdiMC00ZGZiLWIwOWEtMzA5YmEwMTFlZjIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI0VDExNDE0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyNDBmNDU2OTlmNDQ1OWU0Y2RmZDVhODNjZDE3ODU2Yjc5ZDI3ZDNkY2ZhYWZhMWI3NWE2ODhhOGUxNzgzNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.I2d31rNPgrF7zgDHeVOXWMFgzwJm0kW8Y12I9WMMl4I)

Done! I just requested for a pr, please see to it. Thank you!
